### ISSUE TITLE
Rewrite James bond-reference

### ISSUE THREAD

**Issue by viktorlarsson** [EvolveTechnology/evolve-dna#3]
We might not wanna a sexist character as a reference

It’s a little bit like being Bond, James Bond. He is a good example of finding a way out of every tricky situation, but he is also like a chameleon, adapting to every situation. From being chased in the jungle, to going to a gala dinner, he adapts after what the situation requires.

**Comment by perakerberg** [comment]
Agree. Any suggestions for female Bond-like-characters? McGyver is also male, but not sexist. Not very up-to-date either :)

**Comment by perakerberg** [comment]
Maybe a combonation of McGyver and Katniss Everdeen (of the Hunger games)?

**Comment by perakerberg** [comment]
Typ:

It’s a little bit like being McGyver or Katniss Everdeen. To find a way out of every tricky situation and, like a chameleon, adapting to every situation. From opening a door with a paper-clip and a stick of gum to conquer seemingly impossible challenges by outsmarting the competition.

**Comment by gust1n** [comment]
Hmm I like the reference to Katniss, since she's seen in situations all the way from the ballroom to the jungle. I guess that's what the bond reference is trying to say.
